# Generated by Django 4.0.4 on 2022-04-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=200)),
                ('style_number', models.CharField(max_length=5)),
                ('created_by', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.CharField(default='FA20', max_length=4)),
                ('category', models.CharField(default='OUTERWEAR', max_length=25)),
                ('colorway', models.CharField(max_length=25)),
                ('img', models.CharField(max_length=250)),
            ],
        ),
    ]
