# Generated by Django 4.0.4 on 2022-04-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('article_code', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=3)),
                ('supplier', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=250)),
                ('cost', models.CharField(max_length=50)),
                ('material_compostition', models.CharField(max_length=200)),
                ('component_type', models.CharField(default='EX: BUTTON', max_length=200)),
            ],
        ),
    ]
