# Generated by Django 4.0.4 on 2022-04-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='component',
            field=models.ManyToManyField(to='main_app.component'),
        ),
    ]
