# Generated by Django 4.0.4 on 2022-04-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bom_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['style_number']},
        ),
    ]
