# Generated by Django 4.0.4 on 2022-04-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='label',
            field=models.ManyToManyField(to='main_app.label'),
        ),
        migrations.AddField(
            model_name='bom',
            name='trim',
            field=models.ManyToManyField(to='main_app.trim'),
        ),
    ]
