# Generated by Django 4.0.4 on 2022-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_bom_graphic_bom_sketch'),
    ]

    operations = [
        migrations.AddField(
            model_name='trim',
            name='quantity',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trim',
            name='usage',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
