# Generated by Django 4.0.4 on 2022-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_trim_quantity_trim_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trim',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
    ]
