# Generated by Django 4.0.4 on 2022-04-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_trim_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='quantity',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='usage',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
