# Generated by Django 4.0.4 on 2022-04-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_trim_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='usage',
            new_name='placement',
        ),
        migrations.RenameField(
            model_name='trim',
            old_name='usage',
            new_name='placement',
        ),
    ]
