# Generated by Django 4.0.4 on 2022-04-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_rename_usage_label_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='sketch',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='sketch/'),
        ),
    ]
