# Generated by Django 4.0.4 on 2022-04-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_alter_bom_sketch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='graphic',
        ),
    ]
